name: PHPStan

on:
  workflow_dispatch:

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: zip, pdo_sqlite
          coverage: none
          tools: phpstan

      - run: composer install --no-interaction --prefer-dist --no-progress
      - run: phpstan analyse --no-progress
